[package]
name = "concurrent-hashmap"
version = "0.1.0"
authors = ["Alexander Lopatin <alopatindev@gmail.com>"]
edition = "2018"

[dependencies]
num = "0.2.0"
num-traits = "0.2.6"

[dev-dependencies]
num_cpus = "1.10.0"
quickcheck = "0.8.2"
quickcheck_macros = "0.8.0"
rand = "0.6.5"
